# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asearch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rasearch.proto\"6\n\x0bRankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x18\n\x04\x64ocs\x18\x02 \x03(\x0b\x32\n.DocStruct\"h\n\x0cRankResponse\x12)\n\x06result\x18\x01 \x03(\x0b\x32\x19.RankResponse.ResultEntry\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"(\n\nSimRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0b\n\x03\x64oc\x18\x02 \x01(\t\" \n\x0bSimResponse\x12\x11\n\tsim_score\x18\x01 \x01(\x01\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"/\n\rEmbedResponse\x12\x1e\n\nembeddings\x18\x01 \x03(\x0b\x32\n.Embedding\"\x1e\n\tEmbedding\x12\x11\n\tembedding\x18\x01 \x03(\x01\";\n\tDocStruct\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t2\x9b\x01\n\x11\x41SearchSimilarity\x12\'\n\x06ReRank\x12\x0c.RankRequest\x1a\r.RankResponse\"\x00\x12,\n\rTextSimilarty\x12\x0b.SimRequest\x1a\x0c.SimResponse\"\x00\x12/\n\x0cGetEmbedding\x12\r.EmbedRequest\x1a\x0e.EmbedResponse\"\x00\x62\x06proto3')



_RANKREQUEST = DESCRIPTOR.message_types_by_name['RankRequest']
_RANKRESPONSE = DESCRIPTOR.message_types_by_name['RankResponse']
_RANKRESPONSE_RESULTENTRY = _RANKRESPONSE.nested_types_by_name['ResultEntry']
_SIMREQUEST = DESCRIPTOR.message_types_by_name['SimRequest']
_SIMRESPONSE = DESCRIPTOR.message_types_by_name['SimResponse']
_EMBEDREQUEST = DESCRIPTOR.message_types_by_name['EmbedRequest']
_EMBEDRESPONSE = DESCRIPTOR.message_types_by_name['EmbedResponse']
_EMBEDDING = DESCRIPTOR.message_types_by_name['Embedding']
_DOCSTRUCT = DESCRIPTOR.message_types_by_name['DocStruct']
RankRequest = _reflection.GeneratedProtocolMessageType('RankRequest', (_message.Message,), {
  'DESCRIPTOR' : _RANKREQUEST,
  '__module__' : 'asearch_pb2'
  # @@protoc_insertion_point(class_scope:RankRequest)
  })
_sym_db.RegisterMessage(RankRequest)

RankResponse = _reflection.GeneratedProtocolMessageType('RankResponse', (_message.Message,), {

  'ResultEntry' : _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _RANKRESPONSE_RESULTENTRY,
    '__module__' : 'asearch_pb2'
    # @@protoc_insertion_point(class_scope:RankResponse.ResultEntry)
    })
  ,
  'DESCRIPTOR' : _RANKRESPONSE,
  '__module__' : 'asearch_pb2'
  # @@protoc_insertion_point(class_scope:RankResponse)
  })
_sym_db.RegisterMessage(RankResponse)
_sym_db.RegisterMessage(RankResponse.ResultEntry)

SimRequest = _reflection.GeneratedProtocolMessageType('SimRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIMREQUEST,
  '__module__' : 'asearch_pb2'
  # @@protoc_insertion_point(class_scope:SimRequest)
  })
_sym_db.RegisterMessage(SimRequest)

SimResponse = _reflection.GeneratedProtocolMessageType('SimResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMRESPONSE,
  '__module__' : 'asearch_pb2'
  # @@protoc_insertion_point(class_scope:SimResponse)
  })
_sym_db.RegisterMessage(SimResponse)

EmbedRequest = _reflection.GeneratedProtocolMessageType('EmbedRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDREQUEST,
  '__module__' : 'asearch_pb2'
  # @@protoc_insertion_point(class_scope:EmbedRequest)
  })
_sym_db.RegisterMessage(EmbedRequest)

EmbedResponse = _reflection.GeneratedProtocolMessageType('EmbedResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDRESPONSE,
  '__module__' : 'asearch_pb2'
  # @@protoc_insertion_point(class_scope:EmbedResponse)
  })
_sym_db.RegisterMessage(EmbedResponse)

Embedding = _reflection.GeneratedProtocolMessageType('Embedding', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDING,
  '__module__' : 'asearch_pb2'
  # @@protoc_insertion_point(class_scope:Embedding)
  })
_sym_db.RegisterMessage(Embedding)

DocStruct = _reflection.GeneratedProtocolMessageType('DocStruct', (_message.Message,), {
  'DESCRIPTOR' : _DOCSTRUCT,
  '__module__' : 'asearch_pb2'
  # @@protoc_insertion_point(class_scope:DocStruct)
  })
_sym_db.RegisterMessage(DocStruct)

_ASEARCHSIMILARITY = DESCRIPTOR.services_by_name['ASearchSimilarity']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANKRESPONSE_RESULTENTRY._options = None
  _RANKRESPONSE_RESULTENTRY._serialized_options = b'8\001'
  _RANKREQUEST._serialized_start=17
  _RANKREQUEST._serialized_end=71
  _RANKRESPONSE._serialized_start=73
  _RANKRESPONSE._serialized_end=177
  _RANKRESPONSE_RESULTENTRY._serialized_start=132
  _RANKRESPONSE_RESULTENTRY._serialized_end=177
  _SIMREQUEST._serialized_start=179
  _SIMREQUEST._serialized_end=219
  _SIMRESPONSE._serialized_start=221
  _SIMRESPONSE._serialized_end=253
  _EMBEDREQUEST._serialized_start=255
  _EMBEDREQUEST._serialized_end=284
  _EMBEDRESPONSE._serialized_start=286
  _EMBEDRESPONSE._serialized_end=333
  _EMBEDDING._serialized_start=335
  _EMBEDDING._serialized_end=365
  _DOCSTRUCT._serialized_start=367
  _DOCSTRUCT._serialized_end=426
  _ASEARCHSIMILARITY._serialized_start=429
  _ASEARCHSIMILARITY._serialized_end=584
# @@protoc_insertion_point(module_scope)
