# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import asearch_pb2 as asearch__pb2


class ASearchSimilarityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReRank = channel.unary_unary(
                '/ASearchSimilarity/ReRank',
                request_serializer=asearch__pb2.RankRequest.SerializeToString,
                response_deserializer=asearch__pb2.RankResponse.FromString,
                )
        self.TextSimilarty = channel.unary_unary(
                '/ASearchSimilarity/TextSimilarty',
                request_serializer=asearch__pb2.SimRequest.SerializeToString,
                response_deserializer=asearch__pb2.SimResponse.FromString,
                )
        self.GetEmbedding = channel.unary_unary(
                '/ASearchSimilarity/GetEmbedding',
                request_serializer=asearch__pb2.EmbedRequest.SerializeToString,
                response_deserializer=asearch__pb2.EmbedResponse.FromString,
                )


class ASearchSimilarityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReRank(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextSimilarty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASearchSimilarityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReRank': grpc.unary_unary_rpc_method_handler(
                    servicer.ReRank,
                    request_deserializer=asearch__pb2.RankRequest.FromString,
                    response_serializer=asearch__pb2.RankResponse.SerializeToString,
            ),
            'TextSimilarty': grpc.unary_unary_rpc_method_handler(
                    servicer.TextSimilarty,
                    request_deserializer=asearch__pb2.SimRequest.FromString,
                    response_serializer=asearch__pb2.SimResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=asearch__pb2.EmbedRequest.FromString,
                    response_serializer=asearch__pb2.EmbedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ASearchSimilarity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ASearchSimilarity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReRank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ASearchSimilarity/ReRank',
            asearch__pb2.RankRequest.SerializeToString,
            asearch__pb2.RankResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TextSimilarty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ASearchSimilarity/TextSimilarty',
            asearch__pb2.SimRequest.SerializeToString,
            asearch__pb2.SimResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ASearchSimilarity/GetEmbedding',
            asearch__pb2.EmbedRequest.SerializeToString,
            asearch__pb2.EmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
